### ISSUE TITLE
Daniel's Feedback on Bill Page - preliminary

### ISSUE THREAD

**Issue by smplater** [aih/BillMap#208]
(1) HEADER
a. For breadcrumb, add years of the congress for the congress number (116) in the breadcrumb and eliminate the line below the deadline

(2) OVERVIEW
a. Bill stage: does not currently display the dynamic data
b. Related bills: change how you publish the name. Follow the format H.R. XXXX (congress number)
c. Recent actions: we need to find a better phrase than "recent actions" for this
d. Prognosis: no data here. Use Josh's
e. Eliminate the text "read bills" and just keep the icon
f. Consider a light line separating the left and right
g. committees of jurisdiction: try to make this so that it lines up (looks like a box) -- i.e., flush margins
h. move the committee names in the committee of jurisdiction onto one line, and separate the names by a semicolon
i. sponsors: does not appear to be live? or sorted? do we need to develop a heuristic for order of display?
j. the link to full list of sponsors does not work
k. the bottom of the overview section does not have a flat line.

(3). Related bills
a. update the explanatory text. Also note that it is not properly displaying the name of the bill
b. Add tags to related bills for (1) current congress and (2) all congresses
c. Capitalize the first letter in the reason
d. Change "Sponsor (shared)" to "Shared sponsor"
e. Why are "bills related" and "similar bills" different? Should we merge these?
f. Why are there search boxes in all the various sections? Remove them
g. the data does not appear to be live, so it's hard to evaluate
k. fix how many bill names display. (do we need 100 bills?)
l. try to get rid of the horizontal scroll

(4) Understanding the context
a. If there are no matching CRS reports, we should say "No matching CRS reports"
b. Be sure we contain all matching CRS reports, not just the ones from the current congress
c. Show the top 7 or 8 reports, with an accordion to expand and show more
d. Most of the tabs are not working so I cannot evaluate. This includes press, CBO, committee docs, floor.

(5) We are missing the multi-bill graphic, which is in the design.

**Comment by aih** [comment]
Closing. This work has been superceded by other reviews.
