### ISSUE TITLE
CRS Reports do not have links to the actual report

### ISSUE THREAD

**Issue by nkinaba** [aih/BillMap#256]
Some CRS Reports are missing links to the actual report "[No link to report]"

EX: 
H.R. 1 (113th)
https://billmap.govtrack.us/bills/113hr1 

<img width="1145" alt="Screen Shot 2021-03-24 at 4 14 30 PM" src="https://user-images.githubusercontent.com/69855502/112377417-1771b400-8cbc-11eb-94f2-64885b49b401.png">

**Comment by DanielSchuman** [comment]
Connect CRS reports to the website https://www.everycrsreport.com/ not https://crsreports.congress.gov/.  We are already processing all the reports from https://www.everycrsreport.com/ so we should just link to that file location. This will solve the missing links issue.

**Comment by aih** [comment]
@DanielSchuman Do we want to link to the main page (e.g. https://www.everycrsreport.com/reports/R44291.html) or directly to the report (e.g. here: https://www.everycrsreport.com/files/20160726_R44291_da2074247df42c94e12495f26878bfdcceae380a.html)

I've updated the code and server to link to the main page

**Comment by aih** [comment]
Closed with #435
