### ISSUE TITLE
'No data available' statements not showing 

### ISSUE THREAD

**Issue by aih** [aih/BillMap#353]
I've merged, pulled and deployed the changes and the 'emptyTable' statement does not seem to be showing:
![image](https://user-images.githubusercontent.com/217356/117729445-b0428d00-b19f-11eb-916b-46372e9c210d.png)

This may be happening because the dataTable is not being applied to an empty table?

![image](https://user-images.githubusercontent.com/217356/117729563-de27d180-b19f-11eb-8045-ddd3d3ead37b.png)

**Comment by aih** [comment]
Related to #249

**Comment by aih** [comment]
This appears to be fixed in production; maybe it required a cache reset?

![image](https://user-images.githubusercontent.com/217356/119073206-b277c900-b9a1-11eb-8fd9-d45e705cf116.png)
![image](https://user-images.githubusercontent.com/217356/119073226-ba376d80-b9a1-11eb-9ba6-daf27dfd2434.png)
![image](https://user-images.githubusercontent.com/217356/119073248-c4596c00-b9a1-11eb-827e-0713f39041b2.png)
![image](https://user-images.githubusercontent.com/217356/119073265-cc191080-b9a1-11eb-9b59-420868a2be0c.png)

**Comment by smplater** [comment]
This message is not showing for CBO Scores, SAPs, CRS Reports, or Press Statements. It is only showing for relevant committee docs. We need this message to show for all tabs when there is not a document available.

**Comment by aih** [comment]
It is showing for all but Press Statements, now. See https://flatgov.linkedlegislation.com/bills/117hjres44

The statement is set as a DataTable function for all of the other tabs. Press Statements needs to be handled separately.

Closing, and continuing to track under #249

**Comment by aih** [comment]
Fixed in #493. Working and deployed for Press Statements:
![image](https://user-images.githubusercontent.com/217356/124979531-04bf8880-dfe8-11eb-88ca-b9e7dc123c06.png)
