### ISSUE TITLE
Sort list of Companion or Antecedent Bills in descending order by Congress

### ISSUE THREAD

**Issue by aih** [aih/BillMap#383]

**Comment by ayeshamk** [comment]
Overview - Companion or Antecedent Bills

The order in which Identical or Nearly Identical bills should list the bills starting from the most recent congress (Related bills from 117th listed first)

**Comment by ayeshamk** [comment]
@DanielSchuman If we are sorting Companion or Antecedent Bills in descending order by Congress, it makes sense to sort the Related Bills the same way. I implemented scripts for both of the sections.

**Comment by aih** [comment]
I merged and deployed #534, but it only affects 'Related Bills in the Same Congress'. Since the sort is on the full bill number (not just the Congress), it's not clear to me what order this is:
https://billmap.govtrack.us/bills/117hr77
![image](https://user-images.githubusercontent.com/217356/129122314-c26d8b5d-89ce-4ad2-949d-3fbf3683182e.png)

**Comment by DanielSchuman** [comment]
I don't have a preference for the order of bills in the same Congress,
fwiw. I can decide an order but I'm not sure it matters.

**Comment by aih** [comment]
Implemented
