### ISSUE TITLE
Homepage Navigation Menu - Header and Footer

### ISSUE THREAD

**Issue by ayeshamk** [aih/BillMap#386]
HOMEPAGE
Navigation
- Capitalize - us in “About Us”
- Change “Download” to →  “Data Download” and move it to footer
- Move “Documentation” to the Footer 
- Remove “Login” button
- Remove “Bills” from navigation on homepage
- Version number should be moved to footer 
- Navigation should just have → Home, About Us
- Change the image to one of the U.S. Congress

**Comment by ayeshamk** [comment]
> * Change the image to one of the U.S. Congress

@DanielSchuman @nkinaba @smplater is there any specific image that we want?

**Comment by DanielSchuman** [comment]
A picture of the US Capitol would be done. Will this one work?
