### ISSUE TITLE
Homepage - Search Bar filter menu swap and font style change

### ISSUE THREAD

**Issue by ayeshamk** [aih/BillMap#387]
Search Bar

- Change the font color of the search example texts under to search bar to white so it’s more visible to the user 
- Move the Congress filter to the left of the search bar

**Comment by aih** [comment]
Deployed:
![image](https://user-images.githubusercontent.com/217356/127906687-6d00241e-b64e-41a0-aaf9-e83fa5f49a21.png)

**Comment by ayeshamk** [comment]
Search bar swapped as well
![image](https://user-images.githubusercontent.com/13549492/127907152-0b91fe6c-eccc-4bd6-8aea-1cfe7c494470.png)
