### ISSUE TITLE
Develop hover function for Identical or Nearly Identical section in Overview to display short titles

### ISSUE THREAD

**Issue by nkinaba** [aih/BillMap#448]
In the "Identical or Nearly Identical" section, user should be able to see the title or short title of the bill when they hover over it
(same as "Related Bills" section)

**Current**
<img width="916" alt="Screen Shot 2021-06-15 at 1 22 23 PM" src="https://user-images.githubusercontent.com/69855502/122096908-0f1da680-cddd-11eb-8557-96744185b9a9.png">

**Desired** 
<img width="658" alt="Screen Shot 2021-06-15 at 1 25 58 PM" src="https://user-images.githubusercontent.com/69855502/122097447-af73cb00-cddd-11eb-947f-253a26d88e6c.png">

**Comment by ayeshamk** [comment]
@nkinaba the hover feature was only developed for the related bills section. It is not developed for the identical bills section yet. I am changing the issue title to reflect it.

**Comment by DanielSchuman** [comment]
I had thought it was going to be used throughout those upper sections....

**Comment by ayeshamk** [comment]
Completed
