### ISSUE TITLE
Celery configuration: -Q Link Option

### ISSUE THREAD

**Issue by ayeshamk** [aih/BillMap#457]

**Comment by aih** [comment]
This option was removed to allow the email task to work. This issue is to investigate what the option does and whether it will be needed to run the other tasks.

**Comment by aih** [comment]
Changed:
`CELERYD_OPTS="--time-limit=300 --concurrency=3 -Q link -l INFO"`

to
`CELERYD_OPTS="--time-limit=300 --concurrency=3 -l INFO"`

See https://docs.celeryproject.org/en/stable/userguide/daemonizing.html

```
CELERYD_OPTS

Additional command-line arguments for the worker, see celery worker –help for a list. This also supports the extended syntax used by multi to configure settings for individual nodes. See celery multi –help for some multi-node configuration examples.
```

**Comment by aih** [comment]
```
Queue Options:
  --purge, --discard    Purges all waiting tasks before the daemon is started. **WARNING**: This is unrecoverable, and the tasks will be deleted from the messaging
                        server.
  --queues QUEUES, -Q QUEUES
                        List of queues to enable for this worker, separated by comma. By default all configured queues are enabled. Example: -Q video,image
```

So without `Q`, all queues should be enabled. This explains why the option was preventing the email task from working. Closing.
