### ISSUE TITLE
Rename "Identical or Nearly Identical Bills" to "Companion or Antecedent Bills"

### ISSUE THREAD

**Issue by nkinaba** [aih/BillMap#471]
<img width="540" alt="Screen Shot 2021-07-01 at 10 51 50 AM" src="https://user-images.githubusercontent.com/69855502/124144967-6c129100-da5a-11eb-81d9-581f38062833.png">

**Comment by aih** [comment]
Deployed in #488 

NOTE: our current similarity measures don't actually measure 'companion or antecedent' legislation. We are instead using 'identical' or 'nearly identical' text. Some companion or antecedent bills will not be identified this way.
