### ISSUE TITLE
Bills Related To, All Congress and Similar Sections - styling issues

### ISSUE THREAD

**Issue by cybkong** [aih/BillMap#477]
In 'Bills Related To' section, 'All Congress' and 'Similar Sections' tabs have styling issues, not cohesive. Column titles not formatted correctly. 
Story 76
![Screen Shot 2021-07-06 at 11 33 38 AM](https://user-images.githubusercontent.com/86791292/124628248-46b4c700-de4e-11eb-958b-40fcb958907c.png)
![Screen Shot 2021-07-06 at 11 33 50 AM](https://user-images.githubusercontent.com/86791292/124628257-487e8a80-de4e-11eb-96e4-fc28d8dbd785.png)

**Comment by aih** [comment]
Working and deployed.

![image](https://user-images.githubusercontent.com/217356/124801765-103d8180-df0c-11eb-9649-b8b7b9ac2ee3.png)

![image](https://user-images.githubusercontent.com/217356/124801788-1895bc80-df0c-11eb-918f-902e99cd17cb.png)

Closing
