### ISSUE TITLE
Sponsors of Related Measures section Same Congress and Similar Sections tabs

### ISSUE THREAD

**Issue by cybkong** [aih/BillMap#478]
Sponsors of Related Measures section Same Congress and Similar Sections tabs - column title styling issues
*Same Congress tab styling inconsistent - sometimes will display correctly
Story 77

![Screen Shot 2021-07-06 at 11 43 42 AM](https://user-images.githubusercontent.com/86791292/124629476-7b754e00-de4f-11eb-84c7-f649dceb284c.png)

**Comment by leedavidr** [comment]
table column styling issue should be fixed with same commit on #477

**Comment by aih** [comment]
Working and deployed:
![image](https://user-images.githubusercontent.com/217356/124801593-dff5e300-df0b-11eb-8b63-a62da29ef97a.png)

Closing.
