### ISSUE TITLE
Committees and Sponsors section-  Cosponsor Chart

### ISSUE THREAD

**Issue by cybkong** [aih/BillMap#479]
Keep header as Cosponsor
Mark original sponsor as Original Sponsor
Mark original cosponsor as Original Cosponsor
All others are considered co-sponsors
(Story 29)

![Screen Shot 2021-07-06 at 3 38 55 PM](https://user-images.githubusercontent.com/86791292/124657255-49281880-de70-11eb-8f27-d01bc2ed467d.png)

**Comment by aih** [comment]
Deployed and closing:
![image](https://user-images.githubusercontent.com/217356/124801305-8c839500-df0b-11eb-9e12-32f8e1073e47.png)
