### ISSUE TITLE
Bills Related to - Similar Sections tab include export/copy to clipboard

### ISSUE THREAD

**Issue by nkinaba** [aih/BillMap#482]
Include Export/Copy to Clipboard for "Similar Sections" tab in "Bills Related to" section

Current Similar Sections tab view
<img width="1311" alt="Screen Shot 2021-07-07 at 10 22 05 AM" src="https://user-images.githubusercontent.com/69855502/124776221-43344500-df0d-11eb-94b8-bfc2f875dd02.png">

Desired 
<img width="1300" alt="Screen Shot 2021-07-07 at 10 23 03 AM" src="https://user-images.githubusercontent.com/69855502/124776514-8098d280-df0d-11eb-8d83-bbb89f395aef.png">

**Comment by aih** [comment]
Works:
![image](https://user-images.githubusercontent.com/217356/124955846-3de9ff80-dfcc-11eb-8e57-bce4b273c46a.png)

Closing
