### ISSUE TITLE
Understand the Context - styling for "Statements of Administration Policy" tab

### ISSUE THREAD

**Issue by cybkong** [aih/BillMap#484]
Understand the Context section - styling for "Statements of Administration Policy" tab needs to be corrected (the scroll bar on the right and the bottom) 
Story 78

![Screen Shot 2021-07-07 at 11 17 05 AM](https://user-images.githubusercontent.com/86791292/124785467-e046ac00-df14-11eb-9c37-56314d8f3644.png)

**Comment by aih** [comment]
This has been fixed by #486, now deployed:
![image](https://user-images.githubusercontent.com/217356/124801010-30207580-df0b-11eb-9a12-58f0be7a259b.png)
