### ISSUE TITLE
Overview: Identical or Nearly Identical Bills & Related Bills Explanation

### ISSUE THREAD

**Issue by ayeshamk** [aih/BillMap#489]
Include an explanation for related bills. (You can use related bills to identify other measures from this Congress that contain the same or similar text. These can be companion measures or measures that share the similar legislative text throughout the bill or in sections of the bill.)

Include explanation (This section identifies legislation that is virtually identical to the bill you are looking at now from this and other Congresses. It is a fast way to identify companion legislation and antecedent legislation.)

**Comment by aih** [comment]
Deployed in #488 
Closing.

**Comment by ayeshamk** [comment]
Reopening as Daniel would like the explanations to be a pop-up.

**Comment by aih** [comment]
I suggest starting by adding these to `title` attributes, to show on hover. If Daniel wants an actual pop-up, that can be an additional feature.

A downside of pop-ups in this context is that it's not clear how to show the user that the pop-up is available. Maybe an 'i' icon (like the Bootstrap `info` or `info-circle-fill` icon)?

**Comment by DanielSchuman** [comment]
Thank you, Ari. Hover is what I meant. I agree that some kind of icon (like
an [i]) would be a reasonable approach to indicate that.

**Comment by ayeshamk** [comment]
@DanielSchuman @aih Developed info features with hover capabilities that show the explanations.

**Comment by aih** [comment]
Deployed and closing.
