### ISSUE TITLE
Error message for "Relevant Committee Documents" popping up 

### ISSUE THREAD

**Issue by nkinaba** [aih/BillMap#499]
The section for "Relevant Committee Documents" returns an error message.

Issue found at: https://billmap.govtrack.us/bills/116hr436

Text of error message: DataTables warning: table id=relevant-committee-documents-table - Requested unknown parameter '1' for row 0, column 1. For more information about this error, please see http://datatables.net/tn/4

![unnamed](https://user-images.githubusercontent.com/69855502/125096682-6133ae00-e0a3-11eb-82d0-bdeab156608a.png)

**Comment by aih** [comment]
Fixed. Works without pop-up:
![image](https://user-images.githubusercontent.com/217356/125102634-5c193380-e090-11eb-83c1-a96ce060a12b.png)
