### ISSUE TITLE
Overview section - Bill Summary text

### ISSUE THREAD

**Issue by cybkong** [aih/BillMap#507]
If there is no summary text available, say "No Summary Available"
Story #10

<img width="621" alt="Screen Shot 2021-07-29 at 11 35 39 AM" src="https://user-images.githubusercontent.com/86791292/127522638-79c0aaaa-9013-4d3c-819a-d0942d843611.png">

**Comment by ayeshamk** [comment]
duplicated by https://github.com/aih/BillMap/issues/511. Closing.
