### ISSUE TITLE
Overview section- Companion or Antecedent Bills font size

### ISSUE THREAD

**Issue by cybkong** [aih/BillMap#508]
Font size on 'Companion or Antecedent Bills' is smaller than the 'Related Bills' section- should be the same size.
Story #14 

<img width="542" alt="Screen Shot 2021-07-29 at 11 45 41 AM" src="https://user-images.githubusercontent.com/86791292/127523483-7f918eae-2e95-4f82-a59d-57be9915df5f.png">

**Comment by ayeshamk** [comment]
Fixed

![image](https://user-images.githubusercontent.com/13549492/127899106-4b733727-016a-4e23-b9fc-d8a17ea59014.png)

**Comment by aih** [comment]
Deployed
![image](https://user-images.githubusercontent.com/217356/127906778-e3139f5c-e472-4375-b017-2027346c2d66.png)
