### ISSUE TITLE
Overview section- Companion or Antecedent Bills limitation

### ISSUE THREAD

**Issue by cybkong** [aih/BillMap#510]
Limit this section to companion or identical bills. This is basically the same bill, but in the other chamber or in prior Congresses.
Story #17 
<img width="538" alt="Screen Shot 2021-07-29 at 12 06 59 PM" src="https://user-images.githubusercontent.com/86791292/127526647-09573f6f-2668-41b5-89a9-1001b6a43caa.png">

**Comment by ayeshamk** [comment]
> Limit this section to companion or identical bills. This is basically the same bill, but in the other chamber or in prior Congresses.
> Story #17
> <img alt="Screen Shot 2021-07-29 at 12 06 59 PM" width="538" src="https://user-images.githubusercontent.com/86791292/127526647-09573f6f-2668-41b5-89a9-1001b6a43caa.png">

@cybkong It’s not clear from description what to implement. What are we limiting and what are the conditions?

**Comment by aih** [comment]
Closing as ambiguous
