### ISSUE TITLE
Feature whether a bill became a law

### ISSUE THREAD

**Issue by ayeshamk** [aih/BillMap#522]

**Comment by ayeshamk** [comment]
@aih We discussed yesterday that we might already have the data on our end indicating whether a bill became a law or not. Let me know if you see the relevant field in the above screenshots of bills table.

**Comment by aih** [comment]
Thank you for posting these. I don't see the information here. It would be in 'actions' and we haven't stored that. I'll add it to the metadata scraping, but that will take time.

For now, we can mock the feature by creating a 'became_law' Boolean field, where we will store whether the bill directly became law. Then we can manually flag the bills in the 117 congress that became law. You can build the UI based on that

**Comment by aih** [comment]
I've added an 'isEnacted' Boolean field. For now, you can add this for some bills through your Admin panel and then show it in the UI, if the field is True:
![image](https://user-images.githubusercontent.com/217356/128546612-f4b3b2b0-0f8a-495b-882f-13ad089ba483.png)

**Comment by ayeshamk** [comment]
@aih I added a boolean field. Created a PR.

**Comment by aih** [comment]
I've manually marked all bills that became law in the 117th Congress (other than 117hr1319, which wouldn't save from the admin console because it is too big).

The UI looks like this:
![image](https://user-images.githubusercontent.com/217356/128766366-3d2472b2-e98c-4340-8d60-f6233b82afd1.png)
