### ISSUE TITLE
Parse Biden Administration SAP data and store to DB

### ISSUE THREAD

**Issue by ayeshamk** [aih/BillMap#548]

**Comment by aih** [comment]
Download and parse the YAML created by united-states/statements-of-administration-policy. We can remove our scrapy code for SAP.

**Comment by aih** [comment]
The repository is here: https://github.com/unitedstates/statements-of-administration-policy

It's Readme is very detailed and describes the structure of the archives with YAML files for each Administration in the `archives` directory.

For this issue:
1. Create a task that can be used in Celery to download the Biden SAP yaml, parse it and update the BillMap database.
2. Document this process in the Celery update document (.adoc). Note there that the task will need to be updated for future administrations (to point to the correct YAML location)

**Comment by aih** [comment]
Appears to be working; only one document added (HR 4) today
