### ISSUE TITLE
Bug in SAP scraper?

### ISSUE THREAD

**Issue by aih** [aih/BillMap#564]
The new SAP scraper only got one statement from the Biden statements:
![image](https://user-images.githubusercontent.com/217356/131780334-ef2cb9f5-f3f1-4e92-96ee-aa0bb052671c.png)

Is this a bug?

**Comment by ayeshamk** [comment]
@aih is the fix working?

**Comment by aih** [comment]
Yes, it looks like they've been loaded:
![image](https://user-images.githubusercontent.com/217356/131902288-0deee8f0-65c7-4556-b296-7e460807c174.png)
