### ISSUE TITLE
For calendar, create a key for colors, symbols, and other icons  

### ISSUE THREAD

**Issue by smplater** [aih/BillMap#62]
The key should be placed underneath the calendar on the home page.
The user should be able to toggle between showing and hiding the key.

<img width="1078" alt="Image 2020-11-25 at 2 05 29 PM" src="https://user-images.githubusercontent.com/60105995/100271324-4e5ed580-2f27-11eb-8bf1-adc0c7ef5751.png">

![Image 2020-12-15 at 10 42 27 AM](https://user-images.githubusercontent.com/60105995/102237125-4e1c7f00-3ec2-11eb-94d2-1df0fe317fdc.png)

**Comment by juancholarra** [comment]
![image](https://user-images.githubusercontent.com/69854688/103023872-c0bdd800-451c-11eb-8df3-9945e250bdc5.png)

Possible second option to the one @smplater presented.
Added "eye" icon on the left side of the key. Represents option for user to hide and unhide key.

**Comment by aih** [comment]
Implemented, with different style from the mock-ups. 

Closing as `wontfix`
