### ISSUE TITLE
On Calendar, add pop-up modal that shows event details 

### ISSUE THREAD

**Issue by smplater** [aih/BillMap#79]
![Screen Recording 2020-12-15 at 11 35 51 AM (1)](https://user-images.githubusercontent.com/60105995/102244818-cb4bf200-3eca-11eb-9767-cd3d30362eea.gif)

***Event Details box will show when user clicks on side arrow in the event box in the calendar
**The Event details box should show the Chamber, Committee Name, Event Type, Meeting Time

**Comment by aih** [comment]
Closing as `wontfix`
