### ISSUE TITLE
Add data columns to Related Bills section

### ISSUE THREAD

**Issue by smplater** [aih/BillMap#91]
![Image+2020-12-21+at+1 22 19+PM](https://user-images.githubusercontent.com/60105995/102812004-524e0e00-4394-11eb-9da2-07b03bd4f259.png)

Columns in order: Bill Number, Lead Sponsor, Chamber, Status, Compare Bill Text

**Comment by aih** [comment]
The current columns are those we decided on after testing:
![image](https://user-images.githubusercontent.com/217356/131779777-511f9e31-acdc-40a1-b045-49ab4ad220c3.png)
