### ISSUE TITLE
Add question icon after text on "Bills related to ______" section

### ISSUE THREAD

**Issue by juancholarra** [aih/BillMap#93]
![image](https://user-images.githubusercontent.com/69854688/102813449-cee1ec00-4396-11eb-8f15-2e4cee3b964e.png)

** this icon will show a pop-up that will provide context information of what that section is about

**Comment by aih** [comment]
Help text is in-line, which is more user-friendly and accessible:
![image](https://user-images.githubusercontent.com/217356/131779895-14eaf1c5-6185-49c3-a718-9a42b4f5f9c0.png)
